### ISSUE TITLE
smart pkton 无法领取

### ISSUE THREAD

**Issue by yakio** [darwinia-network/smart-app#11]

**Comment by yakio** [comment]
1、从substrate地址到smart转了两笔，分别是0.1 pkton和1pkton。
https://pangolin.subscan.io/account/2qSbd2umtD4KmV2X6Vbtc1J9YiibukynNbpgjg8foarJivL2?tab=transfer

2、一起领取，领取的通知框一直转圈圈，账户详情中pkton余额是0。但subscan里的balance，可以展示出来1.1个/

3、dvm划转页面刷新之后，kton状态还是未领取，可以点击领取，点击后重复上面转圈圈。

**Comment by sxlwar** [comment]
![Kapture 2021-04-21 at 01 18 30](https://user-images.githubusercontent.com/20088392/115438375-e5faf280-a23f-11eb-8d32-952d09310a2a.gif)

**Comment by yakio** [comment]
https://www.subscan.io/tx/0xcc32c957b9bd7173a2f35558c544735f37bd4b099b8cc9ba4c9b3b2dc4db8444
这笔领取交易始终无法成交

**Comment by sxlwar** [comment]
@yakio 这个 issue 可以关了吗
