### ISSUE TITLE
Metamask Support automatic add a network

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/smart-app#17]
@WoeOm please give documents and instructions on this.

**Comment by WoeOm** [comment]
https://github.com/MetaMask/metamask-extension/issues/5101

metamask api: https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods

**Comment by sxlwar** [comment]
![Kapture 2021-05-07 at 21 22 07](https://user-images.githubusercontent.com/20088392/117456232-8ceac880-af7a-11eb-95eb-f1bf9868fb44.gif)
