### ISSUE TITLE
disconnected from wss://crab.darwinia.network: 1000:: Normal Closure

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/smart-app#19]
Can reproduce this when using the switch network (smart menu button).

My suggestion is to use a visible network setting globally to tell the user current network, and make sure rpc/metamask settings consistent. Even more, user might want to customize the rpc link just like the apps rpc settings.

**Comment by sxlwar** [comment]
I will close it, the suggestion mentioned here moved to #22 as an enhancement @yakio
